spring:
  application:
    name: wallet
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_HIBERNATE_DDL_AUTO}
  liquibase:
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG}

server:
  port: 8080

logging:
  level:
    company.wallet: INFO