spring:
  application:
    name: wallet
  jpa:
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 минут
      cache-null-values: false
      key-prefix: "wallet:"
      use-key-prefix: true
    data:
      redis:
        host: localhost
        port: 6379
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0